<h1><center>Numpy</center></h1>
<center>Học viên: Ngô Thị Minh Thư</center>
<center>Email: ngothiminhthu02@gmail.com</center>

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

To use Numpy, we first need to import the numpy package:

In [2]:
import numpy as np

## Arrays
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [3]:
a = np.array([1, 2, 3])  # Create a 1d array
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)       

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [4]:
b = np.array([[1,2,3],[4,5,6]])   # Create a 2d array
print(b)
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

[[1 2 3]
 [4 5 6]]
(2, 3)
1 2 4


In [6]:
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # Create a 3d array
print(c)
print(c.shape)
print(c[0, 0, 0], c[0, 1,1])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
1 4


Numpy also provides many functions to create arrays:

In [7]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [8]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

[[1. 1.]]


In [9]:
c = np.full((2,2), 6) # Create a constant array
print(c)

[[6 6]
 [6 6]]


In [16]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

[[1. 0.]
 [0. 1.]]


In [17]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

[[0.76074685 0.84453228]
 [0.92450036 0.66054685]]


In [19]:
f = np.arange(1,11) # Creating an array using arange()
print(f)

[ 1  2  3  4  5  6  7  8  9 10]


To import Text files into Numpy Arrays, we have two functions in Numpy: 
* numpy.loadtxt( ) – Used to load text file data
* numpy.genfromtxt( ) – Used to load data from a text file, with missing values handled as defined.

### Method 1 : numpy.loadtxt()

In [30]:
with open("dayso1.txt", "w") as file:
    file.writelines(f"{str(i)}\n" for i in f)

In [34]:
file_data = np.loadtxt("example2.txt", dtype=int)
print(file_data)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [33]:
data = np.loadtxt("example3.txt", usecols=1, skiprows=1, dtype='str')
  
for each in data:
    print(each)

Huy
Long
Ha
Kiet


### Method 2 : numpy.genfromtxt()

In [46]:
data = np.genfromtxt("example4.txt", dtype= str, encoding = None, delimiter=" ")
data

array([['1', '2', '3', '4'],
       ['5', '6', '7', '8']], dtype='<U1')

## Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [47]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int32 float64 int64


## Changing Datatype of NumPy Arrays

In [48]:
# Create an array
arr=np.arange(1,10).reshape(3,3)
print("Integer Array:",arr)

# Change datatype of array
arr=arr.astype(float)

# print array
print("Float Array:", arr)

# Check new data type of array
print("Changed Datatype:", arr.dtype)

Integer Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Float Array: [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Changed Datatype: float64


In [49]:
# Change datatype of array
arr=arr.astype(float)

# Check new data type of array
print(arr.dtype)

float64


In [50]:
# Create an array
arr=np.arange(1,10)

# Convert NumPy array to Python List
list1=arr.tolist()
print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


## Array indexing

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:


In [51]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


A slice of an array is a view into the same data, so modifying it will modify the original array.

In [52]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1]) 

2
77


You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array.

In [53]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


Integer array indexing: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [54]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and 
print(a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


In [55]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [56]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b]) 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]


In [57]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [58]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [59]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])

[3 4 5 6]
[3 4 5 6]


##  Descriptive statistics with Python-NumPy

Descriptive statistics describe the basic and important features of data. They help simplify and summarize large amounts of data in a sensible manner.

In [75]:
A = np.array([[10,14,11,7,9.5,15,19],
              [8,9,17,14.5,12,18,15.5], 
              [15,7.5,11.5,10,10.5,7,11],
              [11.5,11,9,12,14,12,7.5]])
B = A.T

In [77]:
print(A)
print(B)

[[10.  14.  11.   7.   9.5 15.  19. ]
 [ 8.   9.  17.  14.5 12.  18.  15.5]
 [15.   7.5 11.5 10.  10.5  7.  11. ]
 [11.5 11.   9.  12.  14.  12.   7.5]]
[[10.   8.  15.  11.5]
 [14.   9.   7.5 11. ]
 [11.  17.  11.5  9. ]
 [ 7.  14.5 10.  12. ]
 [ 9.5 12.  10.5 14. ]
 [15.  18.   7.  12. ]
 [19.  15.5 11.   7.5]]


### Min, Max

It can also be useful to check the minimum and maximum values in your data. If these values are very extreme compared to the mean/median, you know you either have a long tail or outliers, and possibly data errors if they are beyond reasonable. The range is then simply the max-min, telling us how far the data stretches.

In [89]:
print(np.min(A,axis=0)) 
print(np.max(A,axis=1))

[8.  7.5 9.  7.  9.5 7.  7.5]
[19. 18. 15. 14.]


### Mean
Mean means the average of the given values. To compute mean, sum all the values and divide the sum by the number of values.

In [76]:
print(np.mean(B,axis=0)) 
print(np.mean(A,axis=1))

[12.21428571 13.42857143 10.35714286 11.        ]
[12.21428571 13.42857143 10.35714286 11.        ]


### Median
Median is the value where the upper half of the data lies above it and lower half lies below it. In other words, it is the middle value of a data set.

In [79]:
"""
B = [[10.   8.  15.  11.5]
     [14.   9.   7.5 11. ]
     [11.  17.  11.5  9. ]
     [ 7.  14.5 10.  12. ]
     [ 9.5 12.  10.5 14. ]
     [15.  18.   7.  12. ]
     [19.  15.5 11.   7.5]]
"""
a=np.median(B, axis=0)
b=np.median(B, axis=1)
print(a)
print(b)

[11.  14.5 10.5 11.5]
[10.75 10.   11.25 11.   11.25 13.5  13.25]


### Mode
Mode is the value that occurs the most number of times in our data set.

In [85]:
"""
B = [[10.   8.  15.  11.5]
     [14.   9.   7.5 11. ]
     [11.  17.  11.5  9. ]
     [ 7.  14.5 10.  12. ]
     [ 9.5 12.  10.5 14. ]
     [15.  18.   7.  12. ]
     [19.  15.5 11.   7.5]]
"""
from scipy import stats
a=stats.mode(B,axis=0)
print(a)

ModeResult(mode=array([[ 7.,  8.,  7., 12.]]), count=array([[1, 1, 1, 2]]))


### Range
Range is the difference between the maximum and minimum values in the distribution.

In [84]:
"""
B = [[10.   8.  15.  11.5]
     [14.   9.   7.5 11. ]
     [11.  17.  11.5  9. ]
     [ 7.  14.5 10.  12. ]
     [ 9.5 12.  10.5 14. ]
     [15.  18.   7.  12. ]
     [19.  15.5 11.   7.5]]
"""
a=np.ptp(B, axis=0)
print(a)

[12.  10.   8.   6.5]


### Variance
Variance is the average of the squared differences from the mean.

it allows us to measure the spread of a data set around its mean. The observations may or may not be meaningful if observations in data sets are highly spread.

In [86]:
a = np.var(B,axis=0)
print(a)

[13.98979592 12.8877551   6.12244898  3.92857143]


### Standard deviation
Standard deviation is the square root of variance. Standard deviation is on the same scale as the values in the data set.

In [87]:
a = np.std(B,axis=0) 
print(a)

[3.74029356 3.58995196 2.4743583  1.98206242]


### corrcoef
Return Pearson product-moment correlation coefficients.

In [90]:
a = np.corrcoef(B)
print(a)

[[ 1.         -0.42911085 -0.57855561 -0.35344069 -0.1296542  -0.99822653
  -0.54547855]
 [-0.42911085  1.         -0.37884734 -0.59132651 -0.21206037  0.42994939
   0.48530461]
 [-0.57855561 -0.37884734  1.          0.58488715 -0.12427875  0.60177179
   0.46092392]
 [-0.35344069 -0.59132651  0.58488715  1.          0.71113718  0.32484969
  -0.38820648]
 [-0.1296542  -0.21206037 -0.12427875  0.71113718  1.          0.0725954
  -0.75982517]
 [-0.99822653  0.42994939  0.60177179  0.32484969  0.0725954   1.
   0.59204865]
 [-0.54547855  0.48530461  0.46092392 -0.38820648 -0.75982517  0.59204865
   1.        ]]
